# Generated by Django 4.1 on 2022-08-26 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VechicleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('vehicle_type', models.CharField(choices=[('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], default='Two', max_length=10)),
                ('vehicle_model', models.CharField(max_length=30)),
                ('vehicle_description', models.CharField(max_length=100)),
            ],
        ),
    ]
