# Generated by Django 4.1 on 2022-08-26 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechicle', '0002_alter_vechicledetails_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechicledetails',
            name='vehicle_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
